build time -- 2022-03-18 10:25:18.897632
running test_regrid_from_file
Traceback (most recent call last):
  File "src/ESMF/test/regrid_from_file/run_regrid_from_file.py", line 6, in <module>
    import ESMF.api.constants as constants
  File "/glade/scratch/rlong/esmf-testing/intel_18.0.5_openmpi_O_jedwards_pio_update2/src/addon/ESMPy/src/ESMF/__init__.py", line 69, in <module>
    from ESMF.api.esmpymanager import *
  File "/glade/scratch/rlong/esmf-testing/intel_18.0.5_openmpi_O_jedwards_pio_update2/src/addon/ESMPy/src/ESMF/api/esmpymanager.py", line 9, in <module>
    from ESMF.api.constants import *
  File "/glade/scratch/rlong/esmf-testing/intel_18.0.5_openmpi_O_jedwards_pio_update2/src/addon/ESMPy/src/ESMF/api/constants.py", line 3, in <module>
    import numpy as np
ImportError: No module named 'numpy'
Traceback (most recent call last):
  File "setup.py", line 273, in <module>
    'test_regrid_from_file_parallel': TestRegridFromFileParallelCommand})
  File "/usr/lib64/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 192, in run
    subprocess.check_call(cmd)
  File "/usr/lib64/python3.4/subprocess.py", line 558, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'src/ESMF/test/regrid_from_file/run_regrid_from_file.py']' returned non-zero exit status 1
